/**
 * Error code registry — used for telemetry & frontend error mapping.
 * Keeping them in one place prevents duplicate codes.
 */

export const ErrorCodes = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // NotFound
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  PARENT_NOT_FOUND: 'PARENT_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',

  // Conflict
  DUPLICATE_STUDENT_CODE: 'DUPLICATE_STUDENT_CODE',
  DUPLICATE_RECEIPT_NUMBER: 'DUPLICATE_RECEIPT_NUMBER',
  CLASS_FULL: 'CLASS_FULL',

  // Business rules
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
  CANNOT_DELETE_PAID_INVOICE: 'CANNOT_DELETE_PAID_INVOICE',
  INVALID_PAYMENT_STATUS_TRANSITION: 'INVALID_PAYMENT_STATUS_TRANSITION',
  STUDENT_NOT_ACTIVE: 'STUDENT_NOT_ACTIVE',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Infrastructure
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  FILE_IO_ERROR: 'FILE_IO_ERROR',
  EXPORT_FAILED: 'EXPORT_FAILED',

  // Unknown
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
