/**
 * Operations / Dashboard domain — KPIs, charts, alerts, notifications.
 * Plan §15 (Dashboard & Analytics).
 *
 * Iteration 9 — Alert & Notification System Overhaul:
 *   - Alerts now carry an explicit priority (low / medium / high / urgent)
 *     so the UI can sort, filter, and rank by urgency.
 *   - Every alert records its origin (source + sourceLabel) so users can
 *     immediately see which module / entity produced the alert.
 *   - Alerts can be targeted to a specific user, a specific role, or
 *     broadcast to everyone (targetUserId / targetRole both null).
 *   - Alerts can carry an optional `triggeredAt` for timers / scheduled
 *     reminders, distinct from the audit `createdAt`.
 *   - A new `createdBy` field makes manual alerts attributable.
 */
import type { AgingBucket } from "./payment";
import type { Role } from "../../core/rbac/roles";

export type NotificationType =
  | "payment_overdue"
  | "expense_pending"
  | "attendance_alert"
  | "homework"
  | "audit"
  | "system"
  | "message"
  | "custom";

/**
 * Priority ranking — Urgent > High > Medium > Low.
 *
 * Used by the Alerts tab to sort alerts by urgency, and by the Topbar
 * bell to surface the most critical unread alerts first.
 */
export type AlertPriority = "low" | "medium" | "high" | "urgent";

/**
 * Origin category — every alert MUST record where it came from.
 *
 * - `system`          : auto-generated by the platform (overdue, expense pending…)
 * - `manual`          : created by a user via the Alert Creator modal
 * - `workflow`        : raised by a workflow execution
 * - `schedule`        : raised by a scheduled timer (calendar reminder, follow-up call)
 * - `audit`           : raised by the audit subsystem
 */
export type AlertSource =
  | "system"
  | "manual"
  | "workflow"
  | "schedule"
  | "audit";

export interface AppNotification {
  readonly id: string;
  readonly title: string;
  readonly body: string;
  readonly type: NotificationType;
  readonly priority: AlertPriority;
  /** Machine-readable source category. */
  readonly source: AlertSource;
  /** Human-readable module / entity name (e.g. "Module Finances", "Paiements"). */
  readonly sourceLabel: string;
  readonly entityType: string | null;
  readonly entityId: string | null;
  /** Target a specific user (by userId). Null = not user-targeted. */
  readonly targetUserId: string | null;
  /** Target a specific role. Null = not role-targeted. */
  readonly targetRole: Role | null;
  /** Scheduled trigger time for timers / reminders (ISO). Null = immediate. */
  readonly triggeredAt: string | null;
  readonly readAt: string | null;
  readonly createdAt: string;
  /** Actor who created the alert (system userId for auto-generated alerts). */
  readonly createdBy: string;
}

/** Input for manually creating an alert (Alert Creator modal). */
export interface CreateAlertInput {
  readonly title: string;
  readonly body: string;
  readonly type: NotificationType;
  readonly priority: AlertPriority;
  readonly sourceLabel: string;
  readonly entityType?: string | null;
  readonly entityId?: string | null;
  readonly targetUserId?: string | null;
  readonly targetRole?: Role | null;
  readonly triggeredAt?: string | null;
  readonly createdBy: string;
}

export interface DashboardKpi {
  readonly totalStudents: number;
  readonly totalParents: number;
  readonly totalStaff: number;
  readonly monthlyRevenue: number;
  readonly outstandingDebt: number;
  readonly pendingExpenses: number;
  readonly attendanceRateToday: number;
  readonly overdueAlerts: number;
}

export interface RevenuePoint {
  readonly label: string; // "Sep", "Oct", ...
  readonly amount: number;
}

export interface DebtByAgingBucket {
  readonly bucket: AgingBucket;
  readonly amount: number;
  readonly debtorCount: number;
}

export type DemographicSlice = {
  readonly label: string;
  readonly count: number;
  readonly percent: number;
};

export const NOTIFICATION_TYPE_LABELS_FR: Record<NotificationType, string> = {
  payment_overdue: "Paiement en retard",
  expense_pending: "Dépense en attente",
  attendance_alert: "Alerte de présence",
  homework: "Devoir",
  audit: "Audit",
  system: "Système",
  message: "Message",
  custom: "Alerte personnalisée",
};

export const ALERT_PRIORITY_LABELS_FR: Record<AlertPriority, string> = {
  low: "Basse",
  medium: "Moyenne",
  high: "Haute",
  urgent: "Urgente",
};

/**
 * Numeric weight for sorting — higher = more urgent.
 * Used by `sortAlertsByPriority()` in the alerts UI.
 */
export const ALERT_PRIORITY_WEIGHT: Record<AlertPriority, number> = {
  low: 1,
  medium: 2,
  high: 3,
  urgent: 4,
};

export const ALERT_PRIORITY_TONE: Record<
  AlertPriority,
  "neutral" | "info" | "warning" | "danger"
> = {
  low: "neutral",
  medium: "info",
  high: "warning",
  urgent: "danger",
};

export const ALERT_SOURCE_LABELS_FR: Record<AlertSource, string> = {
  system: "Système",
  manual: "Manuelle",
  workflow: "Workflow",
  schedule: "Planifiée",
  audit: "Audit",
};

/**
 * Comparator — sorts alerts by priority (urgent first), then by creation
 * date (newest first) within the same priority. Stable.
 */
export function sortAlertsByPriority<
  T extends { priority: AlertPriority; createdAt: string }
>(alerts: readonly T[]): T[] {
  return [...alerts].sort((a, b) => {
    const pdiff = ALERT_PRIORITY_WEIGHT[b.priority] - ALERT_PRIORITY_WEIGHT[a.priority];
    if (pdiff !== 0) return pdiff;
    return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
  });
}

/**
 * Returns true if a given session should see the alert.
 * Broadcast (null targetUserId + null targetRole) → visible to everyone.
 * User-targeted → visible only to that user.
 * Role-targeted → visible to every user with that role.
 */
export function isAlertVisibleTo(alert: AppNotification, session: {
  userId: string;
  role: Role;
}): boolean {
  if (alert.targetUserId && alert.targetRole) {
    return alert.targetUserId === session.userId || alert.targetRole === session.role;
  }
  if (alert.targetUserId) return alert.targetUserId === session.userId;
  if (alert.targetRole) return alert.targetRole === session.role;
  return true; // broadcast
}
